# Generated by Django 5.1.6 on 2025-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='solved_image',
            field=models.ImageField(blank=True, null=True, upload_to='solved_images/', verbose_name='Фото решения'),
        ),
    ]
